# Generated by Django 2.1.7 on 2019-03-21 03:20

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='address',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
