# Generated by Django 2.1.7 on 2019-03-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0002_auto_20190320_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergoods',
            name='comment',
            field=models.CharField(default='', max_length=256, verbose_name='评论'),
        ),
    ]
