# Generated by Django 2.1 on 2019-05-24 12:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('goods', '0003_remove_indexgoodsbanner_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodssku',
            name='merchant',
        ),
    ]
