# Generated by Django 2.1 on 2019-05-24 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0004_remove_goodssku_merchant'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodssku',
            name='merchant',
            field=models.ForeignKey(default=1, limit_choices_to={'is_merchant': True},
                                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                    verbose_name='商家用户'),
            preserve_default=False,
        ),
    ]
