# Generated by Django 2.1 on 2019-05-27 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0005_goodssku_merchant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodssku',
            name='type',
        ),
        migrations.AddField(
            model_name='goods',
            name='merchant',
            field=models.ForeignKey(default=3, limit_choices_to={'is_merchant': True},
                                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                    verbose_name='商家用户'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goods',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsType',
                                    verbose_name='归属种类'),
            preserve_default=False,
        ),
    ]
