# Generated by Django 2.1 on 2019-05-24 04:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0002_auto_20190522_0708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='merchant',
        ),
    ]
