# Generated by Django 2.1 on 2019-05-26 02:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0003_remove_orderinfo_merchant'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergoods',
            name='order_status',
            field=models.SmallIntegerField(choices=[(1, '待支付'), (2, '待发货'), (3, '待收货'), (4, '待评价'), (5, '已完成')],
                                           default=1, verbose_name='订单状态'),
        ),
    ]
