# Generated by Django 2.1 on 2019-05-26 02:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0004_ordergoods_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='order_status',
        ),
    ]
