# Generated by Django 2.1 on 2019-05-26 02:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0005_remove_orderinfo_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='pay_status',
            field=models.SmallIntegerField(choices=[(1, '未支付'), (2, '已支付')], default=1, verbose_name='支付状态'),
        ),
    ]
