# Generated by Django 2.1.7 on 2019-03-15 02:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('booktest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GoodInfo',
            new_name='GoodsInfo',
        ),
    ]
