# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '3.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtWidgets
from PyQt5.QtCore import QUrl
from PyQt5.QtWebEngineWidgets import QWebEngineView
from PyQt5.QtWidgets import QMainWindow, QApplication, QTableWidgetItem
from select_time import select_time_list


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1205, 681)
        MainWindow.setMinimumSize(QtCore.QSize(1205, 681))
        MainWindow.setMaximumSize(QtCore.QSize(1205, 681))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setObjectName("verticalLayout")


        # Text
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.widget_2)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout.addWidget(self.plainTextEdit)

        # Button
        self.pushButton = QtWidgets.QPushButton(self.widget_2)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.get_time)
        self.verticalLayout.addWidget(self.pushButton)

        # Table
        self.tableWidget = QtWidgets.QTableWidget(self.widget_2)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnWidth(0, 300)
        self.tableWidget.setColumnWidth(1, 200)
        self.tableWidget.itemClicked.connect(self.open_url)
        column_name = ['url', '时间']
        self.tableWidget.setHorizontalHeaderLabels(column_name)
        self.verticalLayout.addWidget(self.tableWidget)

        self.horizontalLayout.addWidget(self.widget_2)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        # self.tableWidget_2 = QtWidgets.QTableWidget(self.widget)
        # self.tableWidget_2.setObjectName("tableWidget_2")
        # self.tableWidget_2.setColumnCount(0)
        # self.tableWidget_2.setRowCount(0)
        # self.verticalLayout_3.addWidget(self.tableWidget_2)
        self.browser = QWebEngineView()
        self.browser.load(QUrl("https://weibo.com/"))
        self.verticalLayout_3.addWidget(self.browser)
        self.horizontalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "获取时间"))

    def get_time(self):
        text = self.plainTextEdit.toPlainText()
        url_list = text.split('\n')
        url_list = [url.strip() for url in url_list]
        data_list = select_time_list(url_list)
        # data_list = [['askdjflas', 'askdjflas'], ['askdjflasd', 'asdiowj']]
        self.my_clear()
        self.set_data(data_list=data_list)

    def my_clear(self):
        row = self.tableWidget.rowCount()
        for row in range(row):
            self.tableWidget.removeRow(0)

    def set_data(self, data_list: list):
        for i, item_list in enumerate(data_list):
            self.tableWidget.insertRow(i)
            for j, item in enumerate(item_list):
                self.tableWidget.setItem(i, j, QTableWidgetItem(str(item)))

    def open_url(self):
        url = self.tableWidget.currentItem().text()
        self.browser.load(QUrl(url))


def show_browser(url: str):  # 显示窗体2
    browser = QWebEngineView()
    # browser.load(QUrl("http://baidu.com"))
    browser.load(QUrl(url))
    browser.show()


class MyMainForm(QMainWindow, Ui_MainWindow):
    def __init__(self, parent=None):
        super(MyMainForm, self).__init__(parent)
        self.setupUi(self)


if __name__ == '__main__':
    # from TabBarStyle import TabBarStyle

    app = QApplication(sys.argv)
    demo = MyMainForm()
    # app.setStyle(TabBarStyle())
    demo.show()
    sys.exit(app.exec_())
