# Generated by Django 2.1 on 2019-05-22 03:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_merchant',
            field=models.BooleanField(default=False, verbose_name='商家标记'),
        ),
    ]
